1:
 id: "1"
 answer: "An Answer"
 words:
  - keyword1
  - word2
  - question3
2:
 id: "2"
 answer: "A whole different answer"
 words:
  - keyword2
  - different
  - words
3:
 id: "3"
 answer: "The team members are ..."
 words:
  - team
  - members
